# Generated by Django 2.0.3 on 2020-07-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default='ROOM_<built-in function id>', max_length=50),
        ),
    ]
