# Generated by Django 2.0.3 on 2020-07-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20200721_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_stock',
            name='ticker',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
