# Generated by Django 2.0.3 on 2020-07-27 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_saved_stock_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_users',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
