# Generated by Django 2.0.3 on 2020-07-27 19:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_room_max_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='starting_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='total_asset_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=20),
        ),
    ]
