# Generated by Django 2.0.3 on 2020-07-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_auto_20200731_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction',
        ),
    ]
