# Generated by Django 2.0.3 on 2020-07-31 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_auto_20200731_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='room',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.Membership'),
        ),
    ]
