# Generated by Django 2.0.3 on 2020-08-03 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_auto_20200731_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
